<?xml version="1.0"?>
    
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">

<xacro:property name="base_l" value="0.07"/>
<xacro:property name="base_w" value="0.06"/>
<xacro:property name="base_h" value="0.04"/>

<xacro:property name="arm_l" value="0.26"/>
<xacro:property name="arm_w" value="0.01"/>
<xacro:property name="arm_h" value="0.01"/>

<xacro:property name="mount_l" value="0.050"/>
<xacro:property name="mount_w" value="0.061"/>
<xacro:property name="mount_h" value="0.07"/>

<xacro:property name="end_effector_1_l" value="0.207"/>
<xacro:property name="end_effector_1_w" value="0.01"/>
<xacro:property name="end_effector_1_h" value="0.01"/>

<xacro:property name="end_effector_2_l" value="0.01"/>
<xacro:property name="end_effector_2_w" value="0.01"/>
<xacro:property name="end_effector_2_h" value="0.08"/>

<xacro:property name="pi" value="3.141592654"/>


	<link name="base">
		<visual>
			<geometry>
				<box size="${base_l} ${base_w} ${base_h}"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
		</visual>
	</link>
	
	<link name="arm">
		<visual>
			<geometry>
				<box size="${arm_l} ${arm_w} ${arm_h}"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
		</visual>
	</link>
	
	<link name="mount">
		<visual>
			<geometry>
				<box size="${mount_l} ${mount_w} ${mount_h}"/>
			</geometry>
			<origin xyz="0 0 0"/>
		</visual>
	</link>
	
	<link name="end_effector_1">
		<visual>
			<geometry>
				<box size="${end_effector_1_l} ${end_effector_1_w} ${end_effector_1_h}"/>
			</geometry>
			<origin xyz="0 0 0"/>
		</visual>
	</link>

	<link name="end_effector_2">
		<visual>
			<geometry>
				<box size="${end_effector_2_l} ${end_effector_2_w} ${end_effector_2_h}"/>
			</geometry>
			<origin xyz="0 0 0"/>
		</visual>
	</link>
	
	<joint name ="base_to_arm" type="prismatic">
		<parent link="base"/>
		<child link="arm"/>
		<axis xyz="1 0 0"/>
		<limit effort="1" lower="0" upper="0.16" velocity="1"/>
		<origin xyz="${((base_l-arm_l)/2) + 0.028} ${-(base_w+arm_w)/2} ${(arm_h-base_h)/2}"/>
	</joint>
	
	<joint name ="arm_to_mount" type="fixed">
		<parent link="arm"/>
		<child link="mount"/>
		<origin xyz="${(arm_l+mount_l)/2} 0.02 0"/>
	</joint>	
	
	<joint name ="mount_to_end_effector_1" type="revolute">
		<parent link="mount"/>
		<child link="end_effector_1"/>
		<axis xyz="1 0 0"/>
		<limit effort="1" lower="-1.58" upper="0" velocity="1"/>
		<origin xyz="${(mount_l+end_effector_1_l)/2} 0.012 -0.008"/>   
	</joint>	
	
	<joint name ="end_effector_1_to_end_effector_2" type="fixed">
		<parent link="end_effector_1"/>
		<child link="end_effector_2"/>
		<origin xyz="${(end_effector_1_l-end_effector_2_l)/2} 0 ${(end_effector_2_h-end_effector_1_h)/2}"/>
	</joint>
	
</robot>
