joint2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint2
    joint_speed: 1.5
    motor:
        id: 31
        init: 2047
        min: 0
        max: 2450

